services:
  - type: web
    name: frontend-next
    env: node
    plan: free
    rootDir: frontend
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 22.11.0
      - key: API_GATEWAY_URL
        value: https://api-gateway-6t3z.onrender.com

  - type: web
    name: api-gateway
    env: python
    plan: free
    rootDir: api_gateway
    buildCommand: pip install -r ../requirements.txt
    startCommand: gunicorn --chdir .. api_gateway.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: CATALOG_SERVICE_URL
        value: https://catalog-service-6auf.onrender.com
      - key: LOANS_SERVICE_URL
        value: https://loans-service-7sne.onrender.com
      - key: RECOMMENDATION_SERVICE_URL
        value: https://recommendation-service-3fdd.onrender.com
      - key: USER_SERVICE_URL
        value: https://user-service-a1qq.onrender.com
      - key: JWT_SECRET
        value: superultrasecreto
      - key: CORS_ORIGINS
        value: https://frontend-next-zst9.onrender.com

  - type: web
    name: catalog-service
    env: python
    plan: free
    rootDir: servico_catalogo
    buildCommand: pip install -r ../requirements.txt
    startCommand: gunicorn --chdir .. servico_catalogo.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: CATALOGO_DB_PATH
        value: /tmp/catalogo.db
      - key: CORS_ORIGINS
        value: https://api-gateway-6t3z.onrender.com,https://frontend-next-zst9.onrender.com

  - type: web
    name: loans-service
    env: python
    plan: free
    rootDir: servico_emprestimos
    buildCommand: pip install -r ../requirements.txt
    startCommand: gunicorn --chdir .. servico_emprestimos.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: CATALOG_SERVICE_URL
        value: https://catalog-service-6auf.onrender.com
      - key: USER_SERVICE_URL
        value: https://user-service-a1qq.onrender.com
      - key: EMPRESTIMOS_DB_PATH
        value: /tmp/emprestimos.db
      - key: CORS_ORIGINS
        value: https://api-gateway-6t3z.onrender.com,https://frontend-next-zst9.onrender.com

  - type: web
    name: recommendation-service
    env: python
    plan: free
    rootDir: servico_recomendacao
    buildCommand: pip install -r ../requirements.txt
    startCommand: gunicorn --chdir .. servico_recomendacao.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: CATALOG_SERVICE_URL
        value: https://catalog-service-6auf.onrender.com
      - key: CORS_ORIGINS
        value: https://api-gateway-6t3z.onrender.com,https://frontend-next-zst9.onrender.com

  - type: web
    name: user-service
    env: python
    plan: free
    rootDir: servico_usuario
    buildCommand: pip install -r ../requirements.txt
    startCommand: gunicorn --chdir .. servico_usuario.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: USUARIO_DB_PATH
        value: /tmp/usuarios.db
      - key: JWT_SECRET
        value: superultrasecreto
      - key: CORS_ORIGINS
        value: https://api-gateway-6t3z.onrender.com
      - key: CORS_ORIGINS
        value: https://api-gateway-6t3z.onrender.com,https://frontend-next-zst9.onrender.com
